// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: coming_product.proto

package stock_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComingProductPrimaryKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComingProdutctId string `protobuf:"bytes,1,opt,name=coming_produtct_id,json=comingProdutctId,proto3" json:"coming_produtct_id,omitempty"`
}

func (x *ComingProductPrimaryKey) Reset() {
	*x = ComingProductPrimaryKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coming_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComingProductPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComingProductPrimaryKey) ProtoMessage() {}

func (x *ComingProductPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_coming_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComingProductPrimaryKey.ProtoReflect.Descriptor instead.
func (*ComingProductPrimaryKey) Descriptor() ([]byte, []int) {
	return file_coming_product_proto_rawDescGZIP(), []int{0}
}

func (x *ComingProductPrimaryKey) GetComingProdutctId() string {
	if x != nil {
		return x.ComingProdutctId
	}
	return ""
}

type ComingProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComingProdutctId string `protobuf:"bytes,1,opt,name=coming_produtct_id,json=comingProdutctId,proto3" json:"coming_produtct_id,omitempty"`
	ComingId         string `protobuf:"bytes,2,opt,name=coming_id,json=comingId,proto3" json:"coming_id,omitempty"`
	ProductId        string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count            int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ComingProduct) Reset() {
	*x = ComingProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coming_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComingProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComingProduct) ProtoMessage() {}

func (x *ComingProduct) ProtoReflect() protoreflect.Message {
	mi := &file_coming_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComingProduct.ProtoReflect.Descriptor instead.
func (*ComingProduct) Descriptor() ([]byte, []int) {
	return file_coming_product_proto_rawDescGZIP(), []int{1}
}

func (x *ComingProduct) GetComingProdutctId() string {
	if x != nil {
		return x.ComingProdutctId
	}
	return ""
}

func (x *ComingProduct) GetComingId() string {
	if x != nil {
		return x.ComingId
	}
	return ""
}

func (x *ComingProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ComingProduct) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateComingProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComingId  string `protobuf:"bytes,2,opt,name=coming_id,json=comingId,proto3" json:"coming_id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count     int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CreateComingProduct) Reset() {
	*x = CreateComingProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coming_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateComingProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComingProduct) ProtoMessage() {}

func (x *CreateComingProduct) ProtoReflect() protoreflect.Message {
	mi := &file_coming_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComingProduct.ProtoReflect.Descriptor instead.
func (*CreateComingProduct) Descriptor() ([]byte, []int) {
	return file_coming_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateComingProduct) GetComingId() string {
	if x != nil {
		return x.ComingId
	}
	return ""
}

func (x *CreateComingProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateComingProduct) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateComingProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComingProdutctId string `protobuf:"bytes,1,opt,name=coming_produtct_id,json=comingProdutctId,proto3" json:"coming_produtct_id,omitempty"`
	ComingId         string `protobuf:"bytes,2,opt,name=coming_id,json=comingId,proto3" json:"coming_id,omitempty"`
	ProductId        string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count            int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateComingProduct) Reset() {
	*x = UpdateComingProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coming_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateComingProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateComingProduct) ProtoMessage() {}

func (x *UpdateComingProduct) ProtoReflect() protoreflect.Message {
	mi := &file_coming_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateComingProduct.ProtoReflect.Descriptor instead.
func (*UpdateComingProduct) Descriptor() ([]byte, []int) {
	return file_coming_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateComingProduct) GetComingProdutctId() string {
	if x != nil {
		return x.ComingProdutctId
	}
	return ""
}

func (x *UpdateComingProduct) GetComingId() string {
	if x != nil {
		return x.ComingId
	}
	return ""
}

func (x *UpdateComingProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateComingProduct) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetListComingProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *GetListComingProductRequest) Reset() {
	*x = GetListComingProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coming_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListComingProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListComingProductRequest) ProtoMessage() {}

func (x *GetListComingProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coming_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListComingProductRequest.ProtoReflect.Descriptor instead.
func (*GetListComingProductRequest) Descriptor() ([]byte, []int) {
	return file_coming_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetListComingProductRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListComingProductRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListComingProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetListComingProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count          int64            `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ComingProducts []*ComingProduct `protobuf:"bytes,2,rep,name=coming_products,json=comingProducts,proto3" json:"coming_products,omitempty"`
}

func (x *GetListComingProductResponse) Reset() {
	*x = GetListComingProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coming_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListComingProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListComingProductResponse) ProtoMessage() {}

func (x *GetListComingProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coming_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListComingProductResponse.ProtoReflect.Descriptor instead.
func (*GetListComingProductResponse) Descriptor() ([]byte, []int) {
	return file_coming_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetListComingProductResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetListComingProductResponse) GetComingProducts() []*ComingProduct {
	if x != nil {
		return x.ComingProducts
	}
	return nil
}

var File_coming_product_proto protoreflect.FileDescriptor

var file_coming_product_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x47, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79,
	0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x74, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f,
	0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x49, 0x64, 0x22, 0x8f,
	0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x74, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f,
	0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x67, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x74, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63,
	0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x63, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x7b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0f,
	0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coming_product_proto_rawDescOnce sync.Once
	file_coming_product_proto_rawDescData = file_coming_product_proto_rawDesc
)

func file_coming_product_proto_rawDescGZIP() []byte {
	file_coming_product_proto_rawDescOnce.Do(func() {
		file_coming_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_coming_product_proto_rawDescData)
	})
	return file_coming_product_proto_rawDescData
}

var file_coming_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coming_product_proto_goTypes = []interface{}{
	(*ComingProductPrimaryKey)(nil),      // 0: stock_service.ComingProductPrimaryKey
	(*ComingProduct)(nil),                // 1: stock_service.ComingProduct
	(*CreateComingProduct)(nil),          // 2: stock_service.CreateComingProduct
	(*UpdateComingProduct)(nil),          // 3: stock_service.UpdateComingProduct
	(*GetListComingProductRequest)(nil),  // 4: stock_service.GetListComingProductRequest
	(*GetListComingProductResponse)(nil), // 5: stock_service.GetListComingProductResponse
}
var file_coming_product_proto_depIdxs = []int32{
	1, // 0: stock_service.GetListComingProductResponse.coming_products:type_name -> stock_service.ComingProduct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coming_product_proto_init() }
func file_coming_product_proto_init() {
	if File_coming_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coming_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComingProductPrimaryKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coming_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComingProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coming_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateComingProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coming_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateComingProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coming_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListComingProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coming_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListComingProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coming_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coming_product_proto_goTypes,
		DependencyIndexes: file_coming_product_proto_depIdxs,
		MessageInfos:      file_coming_product_proto_msgTypes,
	}.Build()
	File_coming_product_proto = out.File
	file_coming_product_proto_rawDesc = nil
	file_coming_product_proto_goTypes = nil
	file_coming_product_proto_depIdxs = nil
}
