// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: stock_product.proto

package stock_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockProductPrimaryKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockProdutctId string `protobuf:"bytes,1,opt,name=stock_produtct_id,json=stockProdutctId,proto3" json:"stock_produtct_id,omitempty"`
}

func (x *StockProductPrimaryKey) Reset() {
	*x = StockProductPrimaryKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockProductPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockProductPrimaryKey) ProtoMessage() {}

func (x *StockProductPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_stock_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockProductPrimaryKey.ProtoReflect.Descriptor instead.
func (*StockProductPrimaryKey) Descriptor() ([]byte, []int) {
	return file_stock_product_proto_rawDescGZIP(), []int{0}
}

func (x *StockProductPrimaryKey) GetStockProdutctId() string {
	if x != nil {
		return x.StockProdutctId
	}
	return ""
}

type StockProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockProdutctId string `protobuf:"bytes,1,opt,name=stock_produtct_id,json=stockProdutctId,proto3" json:"stock_produtct_id,omitempty"`
	StockId         string `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	ProductId       string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count           int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StockProduct) Reset() {
	*x = StockProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockProduct) ProtoMessage() {}

func (x *StockProduct) ProtoReflect() protoreflect.Message {
	mi := &file_stock_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockProduct.ProtoReflect.Descriptor instead.
func (*StockProduct) Descriptor() ([]byte, []int) {
	return file_stock_product_proto_rawDescGZIP(), []int{1}
}

func (x *StockProduct) GetStockProdutctId() string {
	if x != nil {
		return x.StockProdutctId
	}
	return ""
}

func (x *StockProduct) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *StockProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockProduct) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateStockProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockId   string `protobuf:"bytes,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	ProductId string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count     int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CreateStockProduct) Reset() {
	*x = CreateStockProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStockProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockProduct) ProtoMessage() {}

func (x *CreateStockProduct) ProtoReflect() protoreflect.Message {
	mi := &file_stock_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockProduct.ProtoReflect.Descriptor instead.
func (*CreateStockProduct) Descriptor() ([]byte, []int) {
	return file_stock_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStockProduct) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *CreateStockProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateStockProduct) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateStockProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockProdutctId string `protobuf:"bytes,1,opt,name=stock_produtct_id,json=stockProdutctId,proto3" json:"stock_produtct_id,omitempty"`
	StockId         string `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	ProductId       string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count           int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UpdateStockProduct) Reset() {
	*x = UpdateStockProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStockProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockProduct) ProtoMessage() {}

func (x *UpdateStockProduct) ProtoReflect() protoreflect.Message {
	mi := &file_stock_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockProduct.ProtoReflect.Descriptor instead.
func (*UpdateStockProduct) Descriptor() ([]byte, []int) {
	return file_stock_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStockProduct) GetStockProdutctId() string {
	if x != nil {
		return x.StockProdutctId
	}
	return ""
}

func (x *UpdateStockProduct) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *UpdateStockProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateStockProduct) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetListStockProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *GetListStockProductRequest) Reset() {
	*x = GetListStockProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListStockProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListStockProductRequest) ProtoMessage() {}

func (x *GetListStockProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListStockProductRequest.ProtoReflect.Descriptor instead.
func (*GetListStockProductRequest) Descriptor() ([]byte, []int) {
	return file_stock_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetListStockProductRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListStockProductRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListStockProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetListStockProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count         int64           `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	StockProducts []*StockProduct `protobuf:"bytes,2,rep,name=stock_products,json=stockProducts,proto3" json:"stock_products,omitempty"`
}

func (x *GetListStockProductResponse) Reset() {
	*x = GetListStockProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListStockProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListStockProductResponse) ProtoMessage() {}

func (x *GetListStockProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListStockProductResponse.ProtoReflect.Descriptor instead.
func (*GetListStockProductResponse) Descriptor() ([]byte, []int) {
	return file_stock_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetListStockProductResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetListStockProductResponse) GetStockProducts() []*StockProduct {
	if x != nil {
		return x.StockProducts
	}
	return nil
}

var File_stock_product_proto protoreflect.FileDescriptor

var file_stock_product_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x44, 0x0a, 0x16, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x2a,
	0x0a, 0x11, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x49, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x74, 0x63, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x64, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x90, 0x01,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x62, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x22, 0x77, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0e, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x0d,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42, 0x18, 0x5a,
	0x16, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_product_proto_rawDescOnce sync.Once
	file_stock_product_proto_rawDescData = file_stock_product_proto_rawDesc
)

func file_stock_product_proto_rawDescGZIP() []byte {
	file_stock_product_proto_rawDescOnce.Do(func() {
		file_stock_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_product_proto_rawDescData)
	})
	return file_stock_product_proto_rawDescData
}

var file_stock_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stock_product_proto_goTypes = []interface{}{
	(*StockProductPrimaryKey)(nil),      // 0: stock_service.StockProductPrimaryKey
	(*StockProduct)(nil),                // 1: stock_service.StockProduct
	(*CreateStockProduct)(nil),          // 2: stock_service.CreateStockProduct
	(*UpdateStockProduct)(nil),          // 3: stock_service.UpdateStockProduct
	(*GetListStockProductRequest)(nil),  // 4: stock_service.GetListStockProductRequest
	(*GetListStockProductResponse)(nil), // 5: stock_service.GetListStockProductResponse
}
var file_stock_product_proto_depIdxs = []int32{
	1, // 0: stock_service.GetListStockProductResponse.stock_products:type_name -> stock_service.StockProduct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stock_product_proto_init() }
func file_stock_product_proto_init() {
	if File_stock_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockProductPrimaryKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStockProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStockProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListStockProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListStockProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_product_proto_goTypes,
		DependencyIndexes: file_stock_product_proto_depIdxs,
		MessageInfos:      file_stock_product_proto_msgTypes,
	}.Build()
	File_stock_product_proto = out.File
	file_stock_product_proto_rawDesc = nil
	file_stock_product_proto_goTypes = nil
	file_stock_product_proto_depIdxs = nil
}
